### ISSUE TITLE
Failed to execute 'insertAdjacentHTML' on 'Element': The element has no parent.

### ISSUE THREAD

**Issue by nabi-chan** [utterance/utterances#624]
Hello. When I use this plugin in react like this, 

```tsx
export function Comments() {
  return (
    <section
      className="w-full mt-8 print:hidden"
      ref={(element) => {
        if (!element) return;
        const script = document.createElement("script");
        script.setAttribute("src", "https://utteranc.es/client.js");
        script.setAttribute("repo", "KimPinot/plog-comments");
        script.setAttribute("issue-term", "pathname");
        script.setAttribute("label", "comment :speech_balloon:");
        script.setAttribute("theme", "github-light");
        script.setAttribute("crossorigin", "anonymous");
        script.setAttribute("async", "true");
        element.replaceChildren(script);
      }}
    />
  );
}
```

This error always shown :(

```text
Uncaught DOMException: Failed to execute 'insertAdjacentHTML' on 'Element': The element has no parent.
    at https://utteranc.es/client.js:1:1821
    at https://utteranc.es/client.js:1:2220
```

Then, How can I fix it?

**Comment by shafqatalix** [comment]
This is working for me
  
![image](https://user-images.githubusercontent.com/1515257/201825112-10b738b4-00da-4c2f-a86f-8bf375dfe4ae.png)

**Comment by bu-mang** [comment]
Thanks for helping me. it worked!
